blank_issues_enabled: false

contact_links:
  - name: ℹ️ Wiki Pages
    url: https://github.com/EFeru/hoverboard-firmware-hack-FOC/wiki
    about: Please check the Wiki first
  - name: 💬 Telegram Community
    url: https://t.me/joinchat/BHWO_RKu2LT5ZxEkvUB8uw
    about: Connect with the Telegram Community
